export default {
  TIMELINE_LOADED: 'TIMELINE_LOADED',
  ENTRY_ADDED: 'ENTRY_ADDED',
  SHOW_MSG: 'SHOW_MSG',
  HIDE_MSG: 'HIDE_MSG',
  TOGGLE_LOADING: 'TOGGLE_LOADING',
  SET_ACTIVE_NAV: 'SET_ACTIVE_NAV'
};
