export default {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT: 'LOGOUT',
  TIMELINE_LOADED: 'TIMELINE_LOADED',
  ENTRY_ADDED: 'ENTRY_ADDED',
  SHOW_TOAST: 'SHOW_TOAST',
  HIDE_TOAST: 'HIDE_TOAST',
  TOGGLE_LOADING: 'TOGGLE_LOADING',
  SET_ACTIVE_NAV: 'SET_ACTIVE_NAV'
};
